# Generated by Django 5.1.4 on 2024-12-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_index', models.IntegerField()),
                ('school_code', models.IntegerField()),
                ('subject_code', models.IntegerField()),
                ('course_code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
