# Generated by Django 5.1.4 on 2024-12-31 03:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_comment')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='course_list_code_db471a_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_school')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('supplement_code', models.CharField(max_length=255)),
                ('campus_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=1)),
                ('credits', models.IntegerField(null=True)),
                ('prereqs', models.TextField()),
                ('synopsis_url', models.CharField(max_length=255)),
                ('cores', models.ManyToManyField(related_name='course', to='course_list.core')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_list.school')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('number', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('open_status', models.BooleanField()),
                ('subtitle', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=1)),
                ('exam_code_text', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('eligibility', models.CharField(max_length=255)),
                ('cross_listed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('comments', models.ManyToManyField(related_name='section', to='course_list.comment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_list.course')),
            ],
        ),
        migrations.CreateModel(
            name='SectionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('campus_num', models.CharField(max_length=1)),
                ('campus_title', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_list.section')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='course_list_code_ddc2c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_subject')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_list.subject'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['index'], name='course_list_index_0ae9e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('index',), name='unique_section'),
        ),
        migrations.AddIndex(
            model_name='sectionclass',
            index=models.Index(fields=['section', 'day', 'start_time'], name='course_list_section_bafc90_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['school', 'subject', 'code'], name='course_list_school__138b39_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'code', 'supplement_code', 'campus_code'), name='unique_course'),
        ),
    ]
