# Generated by Django 5.1.4 on 2024-12-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
