# Generated by Django 5.1.4 on 2024-12-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reg_index',
        ),
    ]
