# Generated by Django 5.1.4 on 2024-12-31 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='majors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='subtopic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
