# Generated by Django 5.1.4 on 2024-12-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0002_rename_name_course_title_remove_course_reg_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='school_code',
            new_name='administrative_code',
        ),
    ]
