# Generated by Django 5.1.4 on 2024-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0002_alter_course_prereqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
