# Generated by Django 5.1.4 on 2024-12-10 02:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0003_alter_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subtitles',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
