# Generated by Django 5.1.4 on 2024-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0003_remove_school_unique_school_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionclass',
            name='unique_section_class',
        ),
        migrations.RenameField(
            model_name='sectionclass',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='day',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='room',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionclass',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sectionclass',
            constraint=models.UniqueConstraint(fields=('section', 'day', 'start_time'), name='unique_section_class'),
        ),
    ]
