# Generated by Django 5.1.4 on 2024-12-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0004_section_subtitles_alter_section_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='subtitles',
            new_name='subtitle',
        ),
    ]
