# Generated by Django 5.1.4 on 2024-12-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0004_remove_sectionclass_unique_section_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='room',
            field=models.CharField(max_length=255),
        ),
    ]
