# Generated by Django 5.1.4 on 2024-12-10 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0005_rename_subtitles_section_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='cross_listed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None),
        ),
    ]
