# Generated by Django 5.1.4 on 2024-12-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0005_alter_sectionclass_room'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionclass',
            name='unique_section_class',
        ),
        migrations.AlterField(
            model_name='sectionclass',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sectionclass',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
