# Generated by Django 5.1.4 on 2024-12-10 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0007_alter_section_cross_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='core',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
