# Generated by Django 5.1.4 on 2024-12-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0008_course_core'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionclass',
            old_name='campus_name',
            new_name='campus_title',
        ),
    ]
