# Generated by Django 5.1.4 on 2024-12-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0009_rename_campus_name_sectionclass_campus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='exam_code',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='exam_code_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
