# Generated by Django 5.1.4 on 2024-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0010_section_exam_code_section_exam_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['school', 'subject', 'code'], name='course_list_school__138b39_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['code'], name='course_list_code_db471a_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['index'], name='course_list_index_0ae9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionclass',
            index=models.Index(fields=['section', 'day', 'start_time'], name='course_list_section_bafc90_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='course_list_code_ddc2c0_idx'),
        ),
    ]
