# Generated by Django 5.1.4 on 2024-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0013_alter_section_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='comments',
            field=models.ManyToManyField(related_name='section', to='course_list.comment'),
        ),
    ]
