# Generated by Django 5.1.4 on 2024-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0014_alter_section_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cross_listed',
        ),
        migrations.AddField(
            model_name='section',
            name='cross_listed',
            field=models.ManyToManyField(related_name='section', to='course_list.section'),
        ),
    ]
