# Generated by Django 5.1.4 on 2024-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0015_remove_section_cross_listed_section_cross_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cross_listed',
            field=models.ManyToManyField(related_name='following', to='course_list.section'),
        ),
    ]
