# Generated by Django 5.1.4 on 2024-12-12 03:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0016_alter_section_cross_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cross_listed',
        ),
        migrations.AddField(
            model_name='section',
            name='cross_listed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
