# Generated by Django 5.1.4 on 2024-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0017_remove_section_cross_listed_section_cross_listed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='core',
        ),
        migrations.AddField(
            model_name='course',
            name='core',
            field=models.ManyToManyField(related_name='course', to='course_list.core'),
        ),
    ]
