# Generated by Django 5.1.4 on 2024-12-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0018_core_remove_course_core_course_core'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='core',
            new_name='cores',
        ),
    ]
