# Generated by Django 5.1.4 on 2024-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0019_rename_core_course_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='supplement_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
