# Generated by Django 5.1.4 on 2024-12-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0020_course_supplement_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='campus_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
