# Generated by Django 5.1.4 on 2024-12-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0021_course_campus_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'code', 'supplement_code', 'campus_code'), name='unique_course'),
        ),
    ]
